//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D365O_Addin_CreateMethod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddinResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddinResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D365O_Addin_CreateMethod.AddinResources", typeof(AddinResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tpublic static {className} construct()
        ///\t{
        ///\t\treturn new {className}();
        ///\t}.
        /// </summary>
        internal static string construct {
            get {
                return ResourceManager.GetString("construct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto add method.
        /// </summary>
        internal static string DesignerAddinCaption {
            get {
                return ResourceManager.GetString("DesignerAddinCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string exist {
            get {
                return ResourceManager.GetString("exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tpublic static {TableName} find({parms}boolean _forupdate = false)
        ///\t{
        ///\t\t{TableName} {VarName};
        ///
        ///\t\tif ({FieldNames})
        ///\t\t{
        ///\t\t\tif (_forupdate)
        ///\t\t\t{
        ///\t\t\t\t{VarName}.selectForUpdate(_forupdate);
        ///\t\t\t}
        ///
        ///\t\t\tselect firstonly  {VarName}
        ///\t\t\t\t{Where};
        ///\t\t}
        ///\t\treturn {VarName};
        ///\t}.
        /// </summary>
        internal static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tpublic static void main(Args _args)
        ///\t{
        ///\t\t{className} {varName} = {className}::construct();
        ///\t}.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu caption for D365O_Addin_CreateMethod AddIn.
        /// </summary>
        internal static string MainMenuAddInCaption {
            get {
                return ResourceManager.GetString("MainMenuAddInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tpublic container pack()
        ///\t{
        ///\t\treturn [#CurrentVersion, #CurrentList];
        ///\t}.
        /// </summary>
        internal static string pack {
            get {
                return ResourceManager.GetString("pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t#define.CurrentVersion(1)
        ///
        ///\t#localmacro.CurrentList
        ///        
        ///\t#endmacro
        ///.
        /// </summary>
        internal static string packMacro {
            get {
                return ResourceManager.GetString("packMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t[DataMember({MemberValue})]
        ///\tpublic {DataType} {MethodName}({DataType} _{VarName} = {VarName})
        ///\t{
        ///\t\t{VarName} = _{VarName};
        ///\t\treturn {VarName};
        ///\t}.
        /// </summary>
        internal static string parm {
            get {
                return ResourceManager.GetString("parm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///\tpublic {DataType} {MethodName}({DataType} _{VarName} = {VarName})
        ///\t{
        ///\t\t{VarName} = _{VarName};
        ///\t\treturn {VarName};
        ///\t}.
        /// </summary>
        internal static string parmNoDataMember {
            get {
                return ResourceManager.GetString("parmNoDataMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tpublic void run()
        ///\t{
        ///        
        ///\t}.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tpublic boolean unpack(container _packedClass)
        ///\t{
        ///\t\tint version     = RunBase::getVersion(_packedClass);
        ///
        ///\t\tswitch (version)
        ///\t\t{
        ///\t\t\tcase #CurrentVersion:
        ///\t\t\t\t[version, #CurrentList] = _packedClass;
        ///\t\t\t\treturn true;
        ///\t\t\tdefault :
        ///\t\t\t\treturn false;
        ///\t\t}
        ///\t}.
        /// </summary>
        internal static string unpack {
            get {
                return ResourceManager.GetString("unpack", resourceCulture);
            }
        }
    }
}
